<project name="TEST_COMET_NEW1" version="1.1">
    <ProjectDirectory>
        D:\0_all_libero_project\CERN_LHCb\COMET_TEST\designer\programmer\TEST_COMET_NEW1
    </ProjectDirectory>
    <View>
        SingleSTAPLView
    </View>
    <LiberoTargetDevice>
        
    </LiberoTargetDevice>
    <LogFile>
        D:\0_all_libero_project\CERN_LHCb\COMET_TEST\designer\programmer\TEST_COMET_NEW1\TEST_COMET_NEW1.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <programmer status="enable" type="FlashPro4" revision="UndefRev" connection="usb2.0">
        <name>
            88849
        </name>
        <id>
            88849
        </id>
    </programmer>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro5>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
                <ProgrammingMode>
                    JTAGMode
                </ProgrammingMode>
            </FlashPro5>
        </Hardware>
        <Algo type="STAPL">
            <filename>
                D:\0_all_libero_project\CERN_LHCb\COMET_TEST\designer\impl1\TOP_COMET_11_11_2015.stp
            </filename>
            <local>
                projectData\TOP_COMET_11_11_2015.stp
            </local>
            <SelectedAction>
                PROGRAM
            </SelectedAction>
        </Algo>
    </configuration>
</project>
